# \u6570\u636E\u5E93\u8BBF\u95EE\u914D\u7F6E
# \u4E3B\u6570\u636E\u6E90\uFF0C\u9ED8\u8BA4\u7684
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-value: com.mysql.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/facing?characterEncoding=utf-8&useSSL=false
    username: root
    password: allcom
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 5
    minIdle: 5
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    .timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,log4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  # 合并多个DruidDataSource的监控数据
  #spring.datasource.useGlobalDataSourceStat=true
  servlet:
     multipart:
           maxFileSize: 20MB
           maxRequestSize: 20MB

#logging:
#  config: classpath:logback.xml

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#jwt:
#  header: Authorization
#  secret: mySecret
#  expiration: 604800
#  tokenHead: Bearer

#email:
#  ip-address: http://localhost
#  ip-address-link:
#  port: 9005

publicconfig:
  openlog: 1

server:
  port: 9002
  tomcat:
    max-http-post-size: -1